# Generated by Django 4.2.21 on 2025-08-03 20:48

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_user_phone_number_alter_user_groups_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="email_verified",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="user",
            name="verification_token",
            field=models.UUIDField(blank=True, default=uuid.uuid4, null=True),
        ),
    ]
