# Generated by Django 4.2.21 on 2025-08-07 00:42

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0003_user_email_verified_user_verification_token"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="verification_token",
            field=models.UUIDField(
                blank=True, db_index=True, default=uuid.uuid4, null=True
            ),
        ),
    ]
