# Generated by Django 4.2.21 on 2025-08-07 21:21

import django.core.validators
from django.db import migrations, models
import users.models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0004_alter_user_verification_token"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="avatar",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to="avatars/",
                validators=[
                    django.core.validators.FileExtensionValidator(
                        ["jpg", "jpeg", "png"]
                    ),
                    users.models.validate_avatar_size,
                ],
            ),
        ),
    ]
