# Generated by Django 4.2.21 on 2025-08-10 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0006_user_mfa_secret"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="is_paused",
            field=models.BooleanField(default=False),
        ),
    ]
