# Generated by Django 4.2.21 on 2025-01-10 00:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0008_user_email_case_insensitive_unique"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="marketing_opt_in",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="user",
            name="marketing_opt_in_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="user",
            name="marketing_opt_out_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
