# Generated by Django 4.2.21 on 2025-08-11 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0003_order_currency"),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="order",
            name="idx_order_user_created_at",
        ),
        migrations.AddIndex(
            model_name="order",
            index=models.Index(
                condition=models.Q(("is_deleted", False)),
                fields=["user", "-created_at"],
                name="idx_order_user_created_at",
            ),
        ),
    ]
