# Generated by Django 4.2.21 on 2025-08-11 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0004_remove_order_idx_order_user_created_at_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="gift_message",
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name="order",
            name="is_gift",
            field=models.BooleanField(default=False),
        ),
    ]
